name = "OneDimensionalNodes"
uuid = "c5182250-406c-41f5-b9da-836c94d3c2ab"
authors = ["Lucas C Wilcox <lucas@swirlee.com>"]
version = "1.2.0-pre"

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
PrecompileTools = "1"
julia = "1.6"
